### ISSUE TITLE
Hookup Guide

### ISSUE THREAD

**Issue by jaysbeekay** [Materdaddy/Weather_Station#1]
WHilst not an issue - did you happen to have a guide on how you hooked up the weather station to your arduino? Thanks

**Comment by Materdaddy** [comment]
It's a shield from SparkFun, follow these guides:

https://learn.sparkfun.com/tutorials/weather-meter-hookup-guide
https://learn.sparkfun.com/tutorials/weather-station-wirelessly-connected-to-wunderground/all

Note that weather underground shut down their API and this is no longer functional. I use weewx for local display of my weather history now.
